# This is a basic workflow to help you get started with pushing actions to notion
name: Issues to Notion

# Controls when the action will run. 
on:
  issues:
    types: [opened, reopened, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Creates or Updates the issue.
      - name: Issue-to-Notion-STATUS
        uses: NEXGARDEN/issue-to-notion@v1.1.1
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_URL: "https://www.notion.so/nexgarden/a67ce79141c44a8490f6ab7c49852bef?v=97b3d4205f76458584daf80acd804c56"
          PROPERTY_NAME : "Status"
          STATE_OPEN : "Open"
          STATE_CLOSED : "Closed"
        
        # Updates Repo Name
      - name: Issue-to-Notion-REPONAME
        uses: NEXGARDEN/issue-to-notion@v1.1.1
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_URL: "https://www.notion.so/nexgarden/a67ce79141c44a8490f6ab7c49852bef?v=97b3d4205f76458584daf80acd804c56"
          PROPERTY_NAME : "Repository"
          STATE_OPEN : ${{ github.event.repository.name }}
          STATE_CLOSED : ${{ github.event.repository.name }}

        # Updates Repo Name
      - name: Issue-to-Notion-BODY
        uses: NEXGARDEN/issue-to-notion@v1.1.1
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_URL: "https://www.notion.so/nexgarden/a67ce79141c44a8490f6ab7c49852bef?v=97b3d4205f76458584daf80acd804c56"
          PROPERTY_NAME : "Body"
          STATE_OPEN : ${{ github.event.issue.body }}
          STATE_CLOSED : ${{ github.event.issue.body }}
